name: Update Amtrak Plots

on:
  # Run every 10 minutes
  schedule:
    - cron: '*/10 * * * *'
  
  # Allow manual trigger
  workflow_dispatch:

# Allow only one workflow to run at a time to prevent race conditions
concurrency:
  group: update-plots
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          pip install requests
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
      
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("ggplot2", "dplyr", "lubridate", "grid", "tools"), repos="https://cloud.r-project.org")'
      
      - name: Create train_data directories
        run: |
          rm -rf train_data
          mkdir -p train_data/north train_data/south
      
      - name: Generate image ID
        id: img_id
        run: echo "IMG_ID=$(date +%S%M%H%d%m%Y)" >> $GITHUB_OUTPUT
      
      - name: Collect train data
        run: |
          python3 data_collector.py ${{ steps.img_id.outputs.IMG_ID }}
      
      - name: Generate plots with R
        run: |
          Rscript plot_generator.r ${{ steps.img_id.outputs.IMG_ID }}
      
      - name: Update train data JSON
        run: |
          cat new_train_img_data.json > train_img_data.json
          rm new_train_img_data.json
      
      - name: Wait for plots to be generated
        run: sleep 10
      
      - name: Trim old plots
        run: |
          python3 trim_plots.py ${{ steps.img_id.outputs.IMG_ID }}
      
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Commit and push changes
        run: |
          git add plots/ train_img_data.json
          git diff --staged --quiet || git commit -m "Update plots and train data [skip ci] - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

